### ISSUE TITLE
update stylelint-config-recommended to support stylelint 9

### ISSUE THREAD

**Issue by jefbarn** [stylelint/stylelint-config-standard#106]
Hi
I see that you've updated to support stylelint 9, but still requires a dependency on stylelint-config-recommended 2.0.0, which has a dependency on stylelint < 8.
Should update dependency to  stylelint-config-recommended 2.1.0

Thanks.

**Comment by hudochenkov** [comment]
Thank you for noticing. This is a valid point.

**Comment by jeddy3** [comment]
@jefbarn Thanks for the report. Fix was released in `18.2.0`
