### ISSUE TITLE
Add back declaration-block-no-redundant-longhand-properties

### ISSUE THREAD

**Issue by taion** [stylelint/stylelint-config-standard#113]
This was removed as an explicit rule in https://github.com/stylelint/stylelint-config-standard/pull/80/files#diff-168726dbe96b3ce427e7fedce31bb0bcL47, as that rule was present upstream at the time, but the rule was removed in https://github.com/stylelint/stylelint-config-recommended/pull/19, and hence it's no longer here as well.

**Comment by hudochenkov** [comment]
We're not seeing this rule as a best practice for reasons stated in the initial discussion https://github.com/stylelint/stylelint-config-recommended/issues/14. You can add this rule in your config when extending `stylelint-config-standard`.

**Comment by taion** [comment]
My bad. I assumed the removal was unintentional. Thanks!
