### ISSUE TITLE
Trouble with auto format scss

### ISSUE THREAD

**Issue by adFedorovich** [stylelint/stylelint-config-standard#121]
**My code before saving:**

<img width="700" alt="screen1" src="https://user-images.githubusercontent.com/15676325/47796583-b08f8100-dd35-11e8-90af-5f15136fd8ee.png">

**Code after saving:**

<img width="685" alt="screen shot 2018-10-31 at 5 52 56 pm" src="https://user-images.githubusercontent.com/15676325/47796654-d583f400-dd35-11e8-8cfa-2394160d35db.png">

How I can leave my code without changes in similar situations?
_P.S. The same problem with line:_

<img width="513" alt="screen shot 2018-10-31 at 6 01 42 pm" src="https://user-images.githubusercontent.com/15676325/47797343-395aec80-dd37-11e8-9ea6-53560f33a96f.png">

**Comment by adFedorovich** [comment]
**Setting in my IDE:**
```
"[scss]": {
	"editor.formatOnSave": true
}
```

**Comment by jeddy3** [comment]
@adFedorovich Please create an issue in main stylelint repo [using the bug template](https://github.com/stylelint/stylelint/issues/new?template=REPORT_A_BUG.md) so that we can better help you.
