### ISSUE TITLE
Add value-keyword-case

### ISSUE THREAD

**Issue by compeek** [stylelint/stylelint-config-standard#133]
> Clearly describe the bug

It seems to me that `value-keyword-case` is probably missing in `stylelint-config-standard`. It is not called out in the readme as _not_ included, and all of the other `*-case` options are included and set to `lower`.

> Which rule, if any, is the bug related to?

`value-keyword-case`

> What CSS is needed to reproduce the bug?

> What stylelint configuration is needed to reproduce the bug?

> Which version of stylelint are you using?

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

> What did you expect to happen?

I expect `value-keyword-case` to be included in `stylelint-config-standard` for consistency.

> What actually happened (e.g. what warnings or errors did you get)?

`value-keyword-case` is not included in `stylelint-config-standard`.

**Comment by jeddy3** [comment]
@compeek Thanks for raising the issue.

> It seems to me that value-keyword-case is probably missing

I agree. It's probably an oversight that it wasn't included.

> font family names are usually not lowercase, but they would fall under this rule.

The rule ignores `<custom-idents>` of known properties. There [are tests covering](https://github.com/stylelint/stylelint/blob/master/lib/rules/value-keyword-case/__tests__/index.js#L226-L238) font-family names. So, I can't think of a reason off-hand not to include the rule.

---

I'm happy to see this rule be included in the config unless there are any objections?
