### ISSUE TITLE
Fix maximum range on peerDependency

### ISSUE THREAD

**Issue by Arcanemagus** [stylelint/stylelint-config-standard#137]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

The current `peerDependency` definition has no maximum to the allowed range, allowing some potential future version of `stylelint` that isn't actually compatible to be "compatible" but broken.

https://github.com/stylelint/stylelint-config-standard/blob/7ded1fa85387e7adef4e97c9419c0c8ed18737eb/package.json#L35-L37

> Which rule, if any, is this issue related to?

N/A

> What CSS is needed to reproduce this issue?

N/A

> What stylelint configuration is needed to reproduce this issue?

N/A

> Which version of stylelint are you using?

N/A

> How are you running stylelint: CLI, PostCSS plugin, Node API?

N/A

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

N/A

> What did you expect to happen?

A maximum range to be specified preventing future incompatible versions from being used.

> What actually happened (e.g. what warnings or errors you are getting)?

No maximum range is specified.

**Comment by hudochenkov** [comment]
I did this https://github.com/stylelint/stylelint-config-standard/pull/132. And I think this was a mistake, as you pointed out. Future major version of stylelint could break compatibility with current config, which allows for all future versions. We should got back to listing all supported major versions.
