### ISSUE TITLE
Replace *-whitelist/*-blacklist rules with *-allowed-list/*-disallowed-list rules 

### ISSUE THREAD

**Issue by malsf21** [stylelint/stylelint-config-standard#150]
Not sure what template to use here, but we need to update the example `README` with new names and links for the about-to-be-changed ` *-whitelist/*-blacklist` rules with ` *-allowed-list/*-disallowed-list`. This is following the discussion in stylelint/stylelint#4844 and stylelint/stylelint#4845.

Note: this config `README` has no `requirelist` rules (which were changed to `required-list`).

**Comment by jeddy3** [comment]
> Note: this config README has no requirelist rules (which were changed to required-list).

The list is a little out of date and doesn't include some of the newer rules. We should probably add them in by looking at recent new rule changelog entries.
