### ISSUE TITLE
Remove declaration-block-trailing-semicolon?

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-standard#19]
So the config works out-of-the-box with SugarSS.

Looking back through the styleguides it seems some enforce the optional semi, most don't mention it and one suggests not adding it.

I'm happy to remove this one stylistic rule if it means out-of-the-box support for another syntax. Especially as we've been adding "catch subtle coding mistakes" rules to the config recently.

Ref: https://github.com/stylelint/stylelint/issues/978#issuecomment-202312620

If we decide to do this, then I suggest we roll this change in with the pending PR to remove the quote rules. And release them together.

@davidtheclark Thoughts?

**Comment by davidtheclark** [comment]
I think we should leave this rule in because I'd consider it pretty atypical that somebody would *not* want to enforce this.

**Comment by davidtheclark** [comment]
Even with SugarSS in the game, I still think the vast majority of users write SCSS, Less, or CSS, and would expect the trailing semicolon.

**Comment by jeddy3** [comment]
Sgtm.

We'll go with a note in the README instead.
