### ISSUE TITLE
Properties ordering config, revisited

### ISSUE THREAD

**Issue by adamkudrna** [stylelint/stylelint-config-standard#213]
Hello! First off, this is a suggestion not related to the standard config. However I don't want to bloat engine's issues and don't see any better place to put it into. So I'm posting it here.

---

My question is:

> **How do you feel about starting a community-based config for properties order?**

As far as I have seen, developers' preferences regarding CSS properties ordering have a lot in common, no matter the methodology they are inspired by. Therefore I believe there is a potential for sharing it through a common config.

I know, this idea may [not be new](https://github.com/stylelint/stylelint-config-standard/issues/5). But I don't mean it to be part of `stylelint-config-standard`. I think it should be a standalone, opt-in config like `stylelint-config-order-recommended` or similar.

I believe many developers would appreciate such config because:

- There is no such widely acknowledged config yet. The most successful config I've come across is [stylelint-config-recess-order](https://github.com/stormwarning/stylelint-config-recess-order) (seems not bad at all!).
- [A few other](https://github.com/ream88/stylelint-config-idiomatic-order) [open-source](https://github.com/constverum/stylelint-config-rational-order) [configs](https://github.com/d4rkcr0w/stylelint-order-config) [can be found](https://github.com/cahamilton/stylelint-config-property-sort-order-smacss) on GitHub, mostly dead.
- Bootstrap has [its own config](https://github.com/twbs/stylelint-config-twbs-bootstrap/blob/v2.2.4/css/index.js#L38).
- Many other FOSS projects surely have theirs.
- I have [my own shareable config](https://github.com/visionappscz/stylelint-config-visionapps/pull/46) too!

I believe a shared config for properties order would be helpful for a lot of developers. Also, its starting position (and maintenance) will be better under the official `stylelint` namespace.

What do you think? Would it be viable?

I'll be happy to do the technical work if you guys agree with such an idea.

**Comment by Semigradsky** [comment]
You can try https://github.com/theKashey/stylelint-semantic-groups. It sounds like what do you want.

**Comment by jeddy3** [comment]
@adamkudrna Thanks for opening this issue. Sorry that it's taken so long to get around to it. We were mulling https://github.com/stylelint/stylelint/issues/5674 over, which relates to this.

As stylistic rules are now frozen, it's unlikely we'll create an official config for ordering.
