### ISSUE TITLE
New rule for enforcing logical properties

### ISSUE THREAD

**Issue by jd-0001** [stylelint/stylelint-config-standard#214]
### What is the problem you're trying to solve?

**Enforce writing logical properties for RTL compatibility**

I started the project a month ago and in hurry, I have written 1k lines of SCSS without realizing I also need to provide RTL support. At that time I didn't know which [properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) I can use to make them RTL compatible like `margin-inline-start` instead of `margin-left`.

There are a [bunch of properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) and the first thought that come into my mind was what if I can get a hint of some property like `margin-left` can be RTL compatible via using its logical property `margin-inline-start`, with this thought the first name came into my mind was stylelint.

### What solution would you like to see?

Adding a new rule which enforces writing logical properties instead of normal properties.

**Comment by jd-0001** [comment]
something like [this](https://github.com/csstools/stylelint-use-logical) but this is outdated I guess and doesn't have border logical properties.

**Comment by jeddy3** [comment]
@jd-0001 Thanks for the request.

We're tracking the request in https://github.com/stylelint/stylelint/issues/5430. It's likely we'll add a rule once the Four-Directional Shorthand Properties part of the spec is sorted.

In the meantime, you can use [this plugin](https://github.com/Jordan-Hall/stylelint-use-logical-spec) which is pretty feature complete.

Closing here in favour of https://github.com/stylelint/stylelint/issues/5430.
