### ISSUE TITLE
Refactor to remove no-irregular-whitespace as already present in stylelint-config-recommended 

### ISSUE THREAD

**Issue by keganlance** [stylelint/stylelint-config-standard#241]
### What steps are needed to reproduce the bug?

no-irregular-whitespace is already present in  stylelint-config-recommended

### What did you expect to happen?

it not to be included

### What actually happened?

it is included

**Comment by jeddy3** [comment]
@keganlance Thanks for catching that. Pull request welcome.

Is this impacting you or can we classify as a refactor clean up?

**Comment by keganlance** [comment]
@jeddy3 no impact. Can be classified as a refactor clean up!
