### ISSUE TITLE
Add selector-not-notation

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-standard#243]
We are introducing the [selector-not-notation](https://github.com/stylelint/stylelint/tree/main/lib/rules/selector-not-notation) rule in 14.7.0.

We should add it to this config using the "complex" option as it, along with already enabled rules like `color-function-notation: "modern"`, encourages users to write modern CSS code.

**Comment by jeddy3** [comment]
The rule can change specificity, so we'll need to decide where to include it or not.

https://github.com/stylelint/stylelint/issues/5974#issuecomment-1102542370

**Comment by ybiquitous** [comment]
[According to CanIUse.com](https://caniuse.com/css-not-sel-list), it seems that about 90% of users in global can use the *modern* notation.

So, adding the rule to this config sounds good to me. 👍🏼
