### ISSUE TITLE
Use parameterized custom messages

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint-config-standard#263]
### What is the problem you're trying to solve?

This sharable config `stylelint-config-standard` has defined a custom message for a few rules, for example of the `selector-class-pattern`:

https://github.com/stylelint/stylelint-config-standard/blob/f569bb130200e22f606a961cf420b54185fd0c90/index.js#L136-L141

A custom message ([demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AxA8mgBMTkA2EATvJoTFANyYC+IANCAM4CeAdgC4CGAHguI43rgIrAGYBLAOZ9gAHVaZMskIQCueGI2Uk5CxUqYwNYdkQC0YPJwFmADp3bsYhVtswBtefv3KAegAp3TjMALwBdINCABjMATjCAKgBKfzNIkJj4gGokhIASZTovb2xikoMAW01GTkkYN2UAUW5bGBNyXCsBTEYjNtNCTFNMACMYTABrGBHOEYtrepAy-WplsOLV1lpqIA)):

```
Expected class selector to be kebab-case
```

An original message ([demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AxA8mgBMTkA2EATvJoTFANyYC+IANCAM4CeAdgC4CGAHguI43rgIrAGYBLAOZ9gAHVaZMskIQCueGI2Uk5CxUqYwNYdkQC0YPJwFmADp3bsYhVtswBtefv3KAegAp3TjMALwBdINCABjMATjCAKgBKfzNIkJj4gGokhIASZTovb2xqYsUw4rLWWmogA)):

```
Expected class selector ".FOO" to match pattern "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"
```

It would seem more useful if the custom message would become as below:

```
Expected class selector ".FOO" to be kebab-case
```

### What solution would you like to see?

We have added the [experimental feature for custom message formatting](https://stylelint.io/user-guide/configure/#message) via <https://github.com/stylelint/stylelint/pull/6312> and the [14.12.0](https://github.com/stylelint/stylelint/releases/tag/14.12.0) version, so we can use it here.

I suggest like this:

```diff
- message: 'Expected class selector to be kebab-case',
+ message: (value) => `Expected class selector "${value}" to be kebab-case`,
```

Also, we need to update the built-in rules to enable the custom formatting for the rules using a custom message in `stylelint-config-standard`. Like this:

```diff
- message: messages.expected(selector, primary),
+ message: messages.expected,
+ messageArgs: [selector, primary],
```

See also the [built-in rule code](https://github.com/stylelint/stylelint/blob/751acda06a0755ddf0a0603013681173c70bf2c3/lib/rules/selector-class-pattern/index.js#L103).

Target rules can be as below:

- `custom-media-pattern`
- `custom-property-pattern`
- `keyframes-name-pattern`
- `selector-class-pattern`
- `selector-id-pattern`

**Comment by jeddy3** [comment]
Sounds great to me!
