### ISSUE TITLE
Change `import-notation` to `"url"`

### ISSUE THREAD

**Issue by AlexElin** [stylelint/stylelint-config-standard#265]
Why `import-notation` has been set to `string`?
Yes, https://github.com/stylelint/stylelint-config-standard/issues/252 says that "...it's the most common notation used in specs."
But it's unclearly what specs were meant.

For example, the [CSS Cascading and Inheritance Level 5](https://w3c.github.io/csswg-drafts/css-cascade-5/#at-import) spec counts 19 usages of `@import url(..)` and only 3 of `@import "..."`.
This case obviously contradicts to what has been said in the https://github.com/stylelint/stylelint-config-standard/issues/252.

**Comment by jeddy3** [comment]
@AlexElin Thanks for raising the issue.

It seems we made a mistake here. The URL notation aligns more with the forward-facing specs, especially with semi-modern features like [conditional imports](https://w3c.github.io/csswg-drafts/css-cascade-5/#conditional-import) and very modern ones like [cascade layers](https://w3c.github.io/csswg-drafts/css-cascade-5/#layering):

```css
@layer default, theme, components;
@import url(theme.css) layer(theme);
@import url("fallback-layout.css") supports(not (display: flex));
```

We can change it in the next release.
