### ISSUE TITLE
rgba format problem

### ISSUE THREAD

**Issue by CallMeSaltyF1sh** [stylelint/stylelint-config-standard#267]
### Describe the documentation issue

How to prevent rgba from being converted to rgb (as shown in the code block below)？I don't know which rule corresponds to this behavior.
```css
background: rgba(22, 24, 35, 0.7);
background: rgb(22 24 35 / 70%);
```

### What solution would you like to see?

Update this case in the documentation.

**Comment by ybiquitous** [comment]
@CallMeSaltyF1sh Thanks for using the template.

It seems you can turn off the [`color-function-notation`](https://stylelint.io/user-guide/rules/list/color-function-notation) or set `"legacy"` to the rule. See below:

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "color-function-notation": null
  }
}
```

Please see also [README](https://github.com/stylelint/stylelint-config-standard#extending-the-config).
