### ISSUE TITLE
Is the "stylelint-config-recommended" required

### ISSUE THREAD

**Issue by CSM-800** [stylelint/stylelint-config-standard#271]
### Describe the documentation issue

Do I also need to install the "stylelint-config-recommended"? Have only "stylelint-config-standard" installed and works without error. There is nothing in the documentation.

### What solution would you like to see?

A point that explains if you need the "stylelint-config-recommended" or not.

**Comment by ybiquitous** [comment]
@CSM-800 Thanks for using the template.

Since `stylelint-config-standard` has a dependency on `stylelint-config-recommended`, any package managers should install `stylelint-config-recommended` automatically when installing `stylelint-config-standard`.

https://github.com/stylelint/stylelint-config-standard/blob/286effd722d41fa8545df06513b3e0a646f29e1a/package.json#L48-L50

I don't think it's necessary to explain it because this package managers' behavior is common.

What kind of trouble do you have?

**Comment by CSM-800** [comment]
I interpret your answer to my question as "yes".

I installed "stylelint" and "stylelint-config-standard" via npm on macOS and it did not load "stylelint-config-recommended" automatically.

I don't have any errors and don't see any.

Because of the hints everywhere that the standard config extends the recommend and I have no errors although the recommend config is not present I wanted to know this more precisely to be able to understand whether I need this or not.

**Comment by ybiquitous** [comment]
Umm..., is it possible to provide your reproduction info about "don't have any errors and don't see any"? For example:

- `package.json`
- `.stylelintrc.json` (or another format like `.js`)
- Your CSS code

**Comment by CSM-800** [comment]
The error display related to CSS works.

I meant that there is no error because of the missing recommend config. I have installed only "stylint" and "stylelint-config-standard". And still everything works.

Can't describe it better because I don't know english that well.

**Comment by ybiquitous** [comment]
Did you configure Stylelint via `.stylelintrc.json` like this?

```json
{
  "extends": "stylelint-config-standard"
}
```

If doing so, I believe `stylelint-config-recommended` should be loaded automatically: 🤔 

https://github.com/stylelint/stylelint-config-standard/blob/286effd722d41fa8545df06513b3e0a646f29e1a/index.js#L4

See also https://github.com/stylelint/stylelint-config-standard#usage

**Comment by CSM-800** [comment]
That's exactly how I configured it.

**Comment by ybiquitous** [comment]
Then, could you please share your CSS code?

**Comment by CSM-800** [comment]
Yes, my scss code.

```
.entry {
	.entry-content {
		> {
			.wp-block-group,
			.wp-block-columns,
			.wp-block-media-text,
			.wp-block-cover,
			.wp-block-separator {
				margin-top: 3rem;
				margin-bottom: 3rem;
			}
		}

		*:last-child {
			margin-bottom: 0;
		}

		.wp-block-separator {
			border-top: 5px solid $primary;
		}

		.img-4x3 {
			margin-bottom: 0;

			img {
				aspect-ratio: 4/3;
				object-fit: cover;
			}
		}
	}
}
```

**Comment by ybiquitous** [comment]
Thanks. When running the command `npx stylelint a.css`, I can see many errors on my console:

```console
@ybiquitous ➜ /workspaces/codespaces-blank $ npx stylelint a.scss
/workspaces/codespaces-blank/a.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option

a.scss
  2:2  ✖  Expected indentation of 2 spaces          indentation                     
  3:3  ✖  Expected indentation of 4 spaces          indentation                     
  4:4  ✖  Expected indentation of 6 spaces          indentation                     
  5:4  ✖  Expected indentation of 6 spaces          indentation                     
  6:4  ✖  Expected indentation of 6 spaces          indentation                     
  7:4  ✖  Expected indentation of 6 spaces          indentation                     
  8:4  ✖  Expected indentation of 6 spaces          indentation                     
  9:5  ✖  Expected indentation of 8 spaces          indentation                     
 10:5  ✖  Expected indentation of 8 spaces          indentation                     
 11:4  ✖  Expected indentation of 6 spaces          indentation                     
 12:3  ✖  Expected indentation of 4 spaces          indentation                     
 14:3  ✖  Expected indentation of 4 spaces          indentation                     
 15:4  ✖  Expected indentation of 6 spaces          indentation                     
 16:3  ✖  Expected indentation of 4 spaces          indentation                     
 18:3  ✖  Expected indentation of 4 spaces          indentation                     
 19:4  ✖  Expected indentation of 6 spaces          indentation                     
 20:3  ✖  Expected indentation of 4 spaces          indentation                     
 22:3  ✖  Expected indentation of 4 spaces          indentation                     
 23:4  ✖  Expected indentation of 6 spaces          indentation                     
 25:4  ✖  Expected indentation of 6 spaces          indentation                     
 26:5  ✖  Expected indentation of 8 spaces          indentation                     
 27:5  ✖  Expected indentation of 8 spaces          indentation                     
 28:4  ✖  Expected indentation of 6 spaces          indentation                     
 29:3  ✖  Expected indentation of 4 spaces          indentation                     
 30:2  ✖  Expected indentation of 2 spaces          indentation                     
 31:1  ✖  Unexpected missing end-of-source newline  no-missing-end-of-source-newline

26 problems (26 errors, 0 warnings)
```

Can you try to confirm the behavior on my [codespace](https://ybiquitous-curly-computing-machine-9xx7j46w9h795w.github.dev/)?

If using SCSS instead of the standard CSS, I recommend switching to [stylelint-config-standard-scss](https://github.com/stylelint-scss/stylelint-config-standard-scss). See also the following resources:

- https://stylelint.io/user-guide/configure/#plugins
- https://github.com/stylelint/awesome-stylelint#configs

**Comment by CSM-800** [comment]
Ok I realize we are talking past each other :D
I thank you anyway for your help :)

**Comment by ybiquitous** [comment]
Is the problem resolved? If so, please feel free to close this issue.

**Comment by CSM-800** [comment]
Yes, and there was no problem.
I had a question of understanding.
