### ISSUE TITLE
Add `media-feature-range-notation: "context"` rule

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-standard#275]
### What is the problem you're trying to solve?

Consistent range media features.

### What solution would you like to see?

Turn the `media-feature-range-notation` on.

We'll want to use the `context` primary option as it addresses sort comings with the older `prefix` approach. We'll need to wait until

- it's supported in all evergreen browsers ([waiting on Safari](https://caniuse.com/css-media-range-syntax)).
- we add autofix for this option to the rule

**Comment by ybiquitous** [comment]
[Safari 16.4 now supports it!](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes)

<img width="718" alt="image" src="https://user-images.githubusercontent.com/473530/228496837-eb9ac85b-1917-49e1-9402-bd2ae1a56917.png">

In addition, the autofix is coming soon.

- https://github.com/stylelint/stylelint/pull/6742

**Comment by jdelStrother** [comment]
I was surprised this comes on by default when Safari 16.4 is only very recently available and has very low adoption so far. I'm not arguing to change the behaviour, would just love to hear more about the rationale - is the expectation that everyone should be using https://github.com/postcss/postcss-media-minmax to transpile it?

**Comment by ybiquitous** [comment]
This feature is excellent for people, and they should be so happy when all modern browsers support it. So this added rule could be a good opportunity to inform them about the feature.

If people don't need it, they can turn the rule off. Or, they can transpile CSS code with the beautiful Postcss plugin you mentioned.

**Comment by Mister-Hope** [comment]
> This feature is excellent for people, and they should be so happy when all modern browsers support it. So this added rule could be a good opportunity to inform them about the feature.

If people don't need it, they can turn the rule off. Or, they can transpile CSS code with the beautiful Postcss plugin you mentioned.

Yes, I agree that you can add this in changelog with an h1, e.g.:

# Welcome to turn on media-feature-range-notation

But I am definitely surprised to see a rule like this being turned on so carelessly.

See the data from canIUse:

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/33315834/236134584-626251d4-3742-422c-9081-86f353fcc157.png">

It has a low support rage of only <75%, and a one year old chrome even does not support it, and there are so many ios and macOS devices are not upgrading to 16.4 at all.

I don't think this feature should be included at this point, as I think it's more common for **any websites to provide at least one year backwords support for all browsers**

Can we add some notes or commnunity standards, to unify in what case "A feature is already widely supported and can be turned on by default"?
