### ISSUE TITLE
at-rule-no-unknown

### ISSUE THREAD

**Issue by stefanfrede** [stylelint/stylelint-config-standard#28]
FYI: With the new `at-rule-no-unknown` things like `@include` or `@mixin` are considered errors in SCSS.

**Comment by jeddy3** [comment]
@stefanfrede Thanks for the heads up.

I don't think there a 100% clear right thing do here. `at-rule-no-unknown` is a useful rule for everyone writing current or future (using [certain PostCSS plugins](https://github.com/postcss/postcss/blob/master/docs/plugins.md#future-css-syntax)) CSS. 

In previous version of the this config we added other `*-no-unknown` rules:

- `selector-pseudo-class-no-unknown`
- `selector-element-class-no-unknown`
- `selector-type-no-unknown`
- `unit-no-unknown`

So, adding `at-rule-no-unknown` felt consistent.

However, I understand adding `at-rule-no-unknown` does force people who use language extensions (either via a preprocessor like SCSS or via [language extension PostCSS plugins](https://github.com/postcss/postcss/blob/master/docs/plugins.md#language-extensions)), to [extend the config](https://github.com/stylelint/stylelint-config-standard#extending-the-config) and make use of `at-rule-no-unknown`'s [`ignoreAtRules: []` option](https://github.com/stylelint/stylelint/tree/master/src/rules/at-rule-no-unknown#ignoreatrules-array-of-at-rules). But they *only have to do that* if they use at-rule based language extensions like `@mixin`.

So, I guess it comes down to whether we think this config should prioritises standard CSS language features over language extensions, or the other way around? And how important is consistency when deciding what rules are included? While keeping in mind that the config *is extendable* and rules like `at-rule-no-unknown` can be easily turned off or tweaked.

I'm going to label this as a discussion so we can hear a few more opinions before making a decision.

In the meantime:

1. I'll update the "[Extending the config](https://github.com/stylelint/stylelint-config-standard#extending-the-config)" example to include this rule. 
2. Feel free to use  `at-rule-no-unknown`'s [`ignoreAtRules: []` option](https://github.com/stylelint/stylelint/tree/master/src/rules/at-rule-no-unknown#ignoreatrules-array-of-at-rules).

**Comment by davidtheclark** [comment]
I think that the prevalence of non-standard at-rules to extend CSS capabilities, in preprocessors and PostCSS plugins, means this rule should not be included in stylelint-config-standard.
