### ISSUE TITLE
Remove "media-feature-parentheses-space-inside" rule

### ISSUE THREAD

**Issue by Akurganow** [stylelint/stylelint-config-standard#31]
After update to stylelint@7.0.2 from @6.9.0 have error `Undefined rule "media-feature-parentheses-space-inside"`

**Comment by jeddy3** [comment]
Can you double check that you're running `7.0.2` please:

```console
stylelint --version
```

AND: 

```console
./node_modules/.bin/stylelint --version
```

**Comment by Akurganow** [comment]
Sorry, global stylelint was @6.9.0

**Comment by isellsoap** [comment]
I got the same issue, and I’m using stylelint 7.0.2.

The [changelog of release 11.0](https://github.com/stylelint/stylelint-config-standard/releases/tag/11.0.0) states

> Removed: media-feature-parentheses-space-inside rule.

and 

> Added: media-feature-parentheses-space-inside rule.

🤔

**Comment by isellsoap** [comment]
Sorry, my bad. I use `stylelint-webpack-plugin` and its stylelint dependency is `^6.0.1`. :(

**Comment by udisun** [comment]
@isellsoap so how did you solve the problem?

**Comment by isellsoap** [comment]
@udisun https://github.com/vieron/stylelint-webpack-plugin now has the current 7.x dependency of stylelint.
