### ISSUE TITLE
Discussion: declaration-block-no-duplicate-properties enabled by default

### ISSUE THREAD

**Issue by kevinSuttle** [stylelint/stylelint-config-standard#34]
Via https://github.com/stylelint/stylelint/issues/1790#issuecomment-239134959

**Comment by jeddy3** [comment]
I think this was left out by mistake.

@davidtheclark Any objections to adding it? And should we use [one of the options](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-no-duplicate-properties/README.md#options-1) or just disallow all duplicates? In the age of autoprefixer I suspect disallowing all most useful.

**Comment by davidtheclark** [comment]
Sure. I'd go for disabling all.
