### ISSUE TITLE
Usage example doesn't work.

### ISSUE THREAD

**Issue by SeanHayes** [stylelint/stylelint-config-standard#4]
I have a `.stylelintrc` like this:
https://github.com/stylelint/stylelint-config-standard#usage

    $ stylelint /home/user/path/css/*.css
    Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
        at exports.default (/usr/local/lib/node_modules/stylelint/dist/utils/configurationError.js:8:13)
        at getModulePath (/usr/local/lib/node_modules/stylelint/dist/buildConfig.js:120:39)
        at loadExtendedConfig (/usr/local/lib/node_modules/stylelint/dist/buildConfig.js:93:22)
        at /usr/local/lib/node_modules/stylelint/dist/buildConfig.js:82:14

**Comment by jeddy3** [comment]
Hello. Am I right in thinking you've installed `stylelint` and `stylelint-config-standard` globally using the `-g` flag? If so, you'll need to specify the absolute path to `stylelint-config-standard` in your config so `stylelint`  knows where to find it.

I've added an example to the [usage section of the README](https://github.com/stylelint/stylelint-config-standard#usage).

Judging from the error you pasted, your globally installed modules are in `/usr/local/lib/node_modules`, therefore your config should be:

```json
{
  "extends": "/usr/local/lib/node_modules/stylelint-config-standard"
}
```

Let me know if that works for you or not.

**Comment by SeanHayes** [comment]
It worked, thanks!

**Comment by jeddy3** [comment]
No problem :)

**Comment by neojp** [comment]
May I ask why does it need to be an absolute path for a global module? This creates problems working in a team.

**Comment by m-allanson** [comment]
@neojp there's currently an open issue to add support for using globally installed configs without needing an absolute path. See https://github.com/stylelint/stylelint/issues/1973 for details.

**Comment by phpwalter** [comment]
Ues, my lint is installed globally.

This is my `.stylelintrc`

{
  "extends": "L:\etc\node.js\node_modules\stylelint-config-standard",
    "rules": {}
}

I get this error

`Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?`

Thank you

**Comment by Dan503** [comment]
It worked when I ran
```
npm install stylelint-config-standard --save-dev
```
It was missing from my node_modules folder
