### ISSUE TITLE
Undefined rule "declaration-block-no-redundant-longhand-properties"

### ISSUE THREAD

**Issue by liu-dongyu** [stylelint/stylelint-config-standard#41]
With version 13.0.0, i get this error Undefined rule "declaration-block-no-redundant-longhand-properties".
Version 12.0.0 is ok.
![2016-09-06 10-16-37](https://cloud.githubusercontent.com/assets/16187601/18259853/1eedc82c-741b-11e6-8a17-59ebe4d42d02.png)
![2016-09-06 10-14-45](https://cloud.githubusercontent.com/assets/16187601/18259854/20376710-741b-11e6-8b91-a96a50e26c31.png)

**Comment by ntwb** [comment]
Strange everything looks correct, the rule was released in stylelint 7.2, added to stylelint-config-standard in https://github.com/stylelint/stylelint-config-standard/commit/336a1a732e9e11fbdef9fb93481dc94b53e6c9a9.

@liu-dongyu Could you try running `npm update` in your repo, if that still fails remove the `node_modules` folder and reinstall using `npm install` please.

**Comment by liu-dongyu** [comment]
@ntwb Everything is fine after remove the `node_modules` folder and reinstall. Thanks for your help.

**Comment by ntwb** [comment]
Thanks for reporting back 👍
