### ISSUE TITLE
Rule ordering?

### ISSUE THREAD

**Issue by corysimmons** [stylelint/stylelint-config-standard#5]
No opinion about this? Is this considered a divisive rule?

Can rule order affect anything?

**Comment by jeddy3** [comment]
> Is this considered a divisive rule?

Very much so. I found there was little in common between the styleguides used to derive this config. Some advocate alphabetical, while other advocate grouping by their own criteria.

Also, I think the order you choose depends somewhat on your choice of tools e.g. if you're using CSS Modules, you'll probably want the `compose` declaration to come first. Likewise, if you're using `all: initial` you'll probably want that to come before the likes of `align-items`.

This config will get you 80% of the way there. I feel the order of declarations belongs in that last 20% that needs to be discussed and decided upon with your project team.

How does that sound?

**Comment by corysimmons** [comment]
Sounds like a boilerplate and not a standard. Why not rename this `stylelint-config-boilerplate`?

**Comment by corysimmons** [comment]
Actually, nevermind, I'll just make my own standard. Thanks for the tool.

**Comment by julienw** [comment]
See also https://github.com/ream88/stylelint-config-idiomatic-order
(I haven't tried it but it seems to fit this bug :) )
