### ISSUE TITLE
Check mark for enabled rules in documentation 

### ISSUE THREAD

**Issue by pterolex** [stylelint/stylelint-config-standard#55]
Hello, 
[ESLint rules](http://eslint.org/docs/rules/) documentation contains check marks for rules that are enabled in "eslint:recommended".

It would be nice to use the same approach for stylelint-config-standard.

**Comment by jeddy3** [comment]
@pterolex Thank you for the suggestion. `eslint:recommended` is bundled _within_ the `eslint` package, whereas `stylelint-config-standard` is quite a separate entity from `stylelint` itself. So, I think its `stylelint-config-standard`'s responsibility to document which rules it enables and which it doesn't. This is done [within this repo's README](https://github.com/stylelint/stylelint-config-standard#suggested-additions) by listing all the rules _that aren't enabled by this config_.
