### ISSUE TITLE
Include the list of rules used in the readme

### ISSUE THREAD

**Issue by vigneshTheDev** [stylelint/stylelint-config-standard#56]
Hi,
Thanks for the wonderful work. Could you please include the rules used in the documentation?

**Comment by jeddy3** [comment]
We list all the rules _that aren't used_ [within the README](https://github.com/stylelint/stylelint-config-standard/blob/master/README.md#suggested-additions) - you can use this list to quickly find additional rules to extend the config.

The rules _and options_ used are in JSON [here](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js).

Having said that, this is the [2nd request in as many days](https://github.com/stylelint/stylelint-config-standard/issues/55) to document the rules used. As such, @vigneshTheDev would you be willing to contribute a list of rules _that also states how each is configured_ (similar to how the [`stylelint-config-primer`](https://github.com/primer/stylelint-config-primer#configured-lints) does it.)? I think that would be more useful than just linking through to the rule.

e.g.

---

### At-rule

* [at-rule-name-case](http://stylelint.io/user-guide/rules/at-rule-name-case/): At-rules must be in written in lowercase.

### Color

* [color-hex-case](http://stylelint.io/user-guide/rules/color-hex-case/): Hex colors must be written in lowercase.
* [color-hex-length](http://stylelint.io/user-guide/rules/color-hex-length/): Hex colors must, where available, use shorthand notation.

#### Declaration

* [declaration-empty-line-before](http://stylelint.io/user-guide/rules/declaration-empty-line-before): There must be an empty line before each declaration unless the declaration is preceded by a comment, declaration or opening brace, or is inside a single line block. If the declaration is preceded by a comment or declaration then there must be no empty line. If it is preceded by an opening brace or is inside a single line block then it is ignored.

---

That last one is quite verbose as the secondary option for the rule is configured with four conditionals:

```js
"declaration-empty-line-before": [ "always", {
      "except": [
        "after-declaration",
        "first-nested",
      ],
      "ignore": [
        "after-comment",
        "inside-single-line-block",
      ],
    } ],
```

**Comment by davidtheclark** [comment]
@jeddy3 Do you really think this is worth the maintenance? The JSON itself is very legible. Maybe we just need a more clear explanation in the README that "To see the rules that this config uses, please read the config itself."

**Comment by davidtheclark** [comment]
Whatever you think is best! I just wanted to raise the question, but defer.
