### ISSUE TITLE
Why `number-leading-zero` rule is set as `always`?

### ISSUE THREAD

**Issue by frenzzy** [stylelint/stylelint-config-standard#59]
Readme says:
> It is derived from the common rules found within a handful of CSS styleguides, including:
> - [The Idiomatic CSS Principles](https://github.com/necolas/idiomatic-css)
> - [Github's PrimerCSS Guidelines](http://primercss.io/guidelines/#scss)
> - [Google's CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.xml#CSS_Formatting_Rules)
> - [Airbnb's Styleguide](https://github.com/airbnb/css#css)
> - [@mdo's Code Guide](http://codeguide.co/#css)

But `Google's CSS Style Guide` and `@mdo's Code Guide` says:
> [Omit leading “0”s in values.](https://google.github.io/styleguide/htmlcssguide.xml?showone=Leading_0s#Leading_0s)
> Do not use put 0s in front of values or lengths between -1 and 1.
> `font-size: .8em;`

> Don't prefix property values or color parameters with a leading zero (e.g., `.5` instead of `0.5` and `-.5px` instead of `-0.5px`).

`Github's PrimerCSS Guidelines` just do not use [leading zero in examples](http://primercss.io/guidelines/#examples)

And other guides do not mention the leading zero.

So, maybe change [`number-leading-zero`](https://github.com/stylelint/stylelint/tree/master/lib/rules/number-leading-zero) rule to `never` or at least to `null`?

**Comment by davidtheclark** [comment]
Airbnb and Idiomatic CSS both use the leading zero. I don't see mention in the others.

I am very much inclined to use the leading zero. I think it makes the code more quickly legible.

If this is too controversial, we can consider dropping the rule from the config — but we will not switch to `never`.

**Comment by jeddy3** [comment]
> Airbnb and Idiomatic CSS both use the leading zero. I don't see mention in the others. I am very much inclined to use the leading zero. I think it makes the code more quickly legible.

Agreed.
