### ISSUE TITLE
Use standard config as default?

### ISSUE THREAD

**Issue by gitanupam** [stylelint/stylelint-config-standard#62]
How about having the setting 'Use standard' checked by default and 'Disable when no config file is found' unchecked by default?

This is to ensure that it works 'out of the box' and the users can then apply their own config file if they feel the need for it.

**Comment by jeddy3** [comment]
This seems to be about linter-stylelint. Please post [there instead](https://github.com/AtomLinter/linter-stylelint).

**Comment by gitanupam** [comment]
Sorry - will do.

**Comment by gitanupam** [comment]
(opened at https://github.com/AtomLinter/linter-stylelint/issues/320)
