### ISSUE TITLE
font-family-no-duplicate-names: Ignore "monospace" by default

### ISSUE THREAD

**Issue by steffenweber** [stylelint/stylelint-config-standard#63]
I think stylelint-config-standard should enable the option `{"ignoreFontFamilyNames": "monospace"}` by default. See the discussion in [StyleLint Issue #2086](https://github.com/stylelint/stylelint/issues/2086).

What you you think?

**Comment by jeddy3** [comment]
I'm not sure working around this issue with a hack should be the responsibility of this config. At the moment it is a choice of the user whether to address the issue by extending the config and overriding the rule, _or_ by being explicit _within the code base itself_ and using a `stylelint-disable font-family-no-duplicate-names` command.

**Comment by steffenweber** [comment]
Working around this issue in my own `.stylelintrc` is definetely easy. I'm fine if it stays the way it is.

**Comment by jeddy3** [comment]
> At the moment it is a choice of the user whether to address the issue by extending the config and overriding the rule

As no further input and for the reason I outlined above, I'm going to close this.
