### ISSUE TITLE
Is it good to set `number-leading-zero` to ["never"]?

### ISSUE THREAD

**Issue by willowcheng** [stylelint/stylelint-config-standard#69]
Read common rules listed in README for leading zero and here are what I find:

- [The Idiomatic CSS Principles](https://github.com/necolas/idiomatic-css): **not specified** and use leading zero in example
- [Github's PrimerCSS Guidelines](http://primercss.io/guidelines/#scss): **not specified** and omit leading zero in examples
- [Google's CSS Style Guide](https://google.github.io/styleguide/htmlcssguide.html): **omit leading “0”s in values. Do not use put 0s in front of values or lengths between -1 and 1.**
- [Airbnb's Styleguide](https://github.com/airbnb/css#css): **not specified** and use leading zero in examples
- [@mdo's Code Guide](http://codeguide.co/#css): **Don't prefix property values or color parameters with a leading zero (e.g., `.5` instead of `0.5` and `-.5px` instead of `-0.5px`).**

Personally I like non leading zero more as it's neater.

**Comment by willowcheng** [comment]
Just found it's discussed.

**Comment by ntwb** [comment]
We won't switch to `never`, see #59 for more details, I'm not sure we've had enough requests to consider dropping the rule either, I think more people use a leading zero than do not.
