### ISSUE TITLE
Can you help in how to make npm module for my own .stylelintrc file like you have stylelint-config-standard ?

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint-config-standard#79]
I have my own custom `.stylelintrc` file but I don't know what to do next

**Comment by jeddy3** [comment]
This issue tracker is for issues with `stylelint-config-standard`. Stackoverflow is the best resource for questions and answers.

Having said that, there's a video guide at npmjs.com that will help you - https://docs.npmjs.com/getting-started/publishing-npm-packages . As long as you've a `package.json` (with all correct name etc!) and an `index.js` that [exports](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js#L3) your config, then you should be fine.
