### ISSUE TITLE
Autoformat not working anymore since update from 17.0.0 -> 18.0.0 

### ISSUE THREAD

**Issue by jimblue** [stylelint/stylelint-config-standard#99]
As explain in the title, autoformat is not working anymore with 18.0.0 using stylefmt.

Any idea why? Is it possible to fix this?

Thank you

**Reference**
https://github.com/mrmlnc/vscode-stylefmt/issues/138

**Comment by hudochenkov** [comment]
There is no problem with config: https://github.com/stylelint/stylelint/issues/3042#issuecomment-347578941
